config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tweets#index'
  patch 'tweets/:id/edit' => 'tweets#update'
  resources :tweets do
  resources :comments, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates :text, {presence: true, length: { in: 3..40 } }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :text, {length: { in: 3..100 } }
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 8..16
  has_many :tweets
  has_many :comments
  validates :name, length: { in: 1..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @tweet = Tweet.find(params[:tweet_id])
    @comments = @tweet.comments.includes(:user).order("created_at DESC")
  end

  def create
    @tweet = Tweet.find(params[:tweet_id])
    @comment = Comment.create(text: comment_params[:text], tweet_id: comment_params[:tweet_id], user_id: current_user.id)
    @comments = @tweet.comments.includes(:user).order("created_at DESC")
  end

private
  def comment_params
    params.permit(:text, :tweet_id)
  end
  
end

app/controllers/helpers/application_helper.rb
module ApplicationHelper
end

app/controllers/helpers/comments_helper.rb
module CommentsHelper
end

app/controllers/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/controllers/helpers/sessions_helper.rb
module SessionsHelper
end

app/controllers/helpers/tweets_helper.rb
module TweetsHelper
end

app/controllers/helpers/users_helper.rb
module UsersHelper
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.order("created_at DESC")
  end

  def new
    @tweet = Tweet.new

  end

  def create
    @tweet = Tweet.create(text: tweet_params[:text], user_id: current_user.id)
    if @tweet.save
      redirect_to :root
      flash[:notice] = "投稿が完了しました"
    else
      render 'new'
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweets = Tweet.all.order("created_at DESC")
    if @tweet.update(tweet_params)
    redirect_to tweets_path
    flash[:notice] = "ツイートを編集しました"
    else
    render 'edit'
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    if @tweet.destroy
      render 'destroy'
      flash[:notice] = "ツイートを削除しました"
    end
  end

private
  def tweet_params
    params.permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by(email: session_params[:email], encrypted_password: session_params[:encrypted_password])
    if @user
      redirect_to :root
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:email]
      @encrypted_password = params[:encrypted_password]
      render "devise/sessions/new"
    end
  end

  private
  def session_params
    params.permit(:email, :encrypted_password)
  end

end
  

app/views/comments/_comment.html.haml
.comments-chat-main
  .tweets-block
    .user-name
      = @tweet.user.name
    .messages
      = @tweet.text
      - if user_signed_in? && current_user.id == @tweet.user_id
        = link_to "編集", "/tweets/#{@tweet.id}/edit", method: :get, class: "comments-edit"
        = link_to "削除", "/tweets/#{@tweet.id}", method: :delete, class: "comments-delete"
    .comments-time
      = @tweet.created_at.strftime("%Y/%m/%d %H:%M")
  .comments《コメント一覧》
  .comments-scroll
    - @comments.each do |comment|
      .comments-user-name 
        = comment.user.name
        ：
      .comments-index-text 
        = comment.text
      .comments-index-time
        = comment.created_at.strftime("%Y/%m/%d %H:%M")

  .comments-form
    = form_tag("/tweets/#{@tweet.id}/comments", method: :post) do
      %h3.comments-new-tweets
        %textarea{placeholder: "返信する内容を入力して下さい", name: "text", class: "comments-text"}
        %input{type: "submit", class: "comments-submit"}/ 

app/views/comments/create.html.haml
= render "comment"


-# <% if current_user %>
-#       <%= form_tag("/tweets/#{@tweet.id}/comments", method: :post) do %>
-#         <textarea cols="30" name="text" placeholder="コメントする" rows="2"></textarea>
-#         <input type="submit" value="SENT">
-#       <% end %>
-#     <% end %>
-#     <div class="comments">   
-#       <h4>＜コメント一覧＞</h4>
-#       <% if @comments %>
-#         <% @comments.each do |comment| %>
-#           <p>
-#             <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
-#             <%= comment.text %>
-#           </p>
-#         <% end %>
-#       <% end %>
-#     </div>
-#   </div>
-# </div>

app/views/comments/index.html.haml
= render "comment"

app/views/layouts/_error.html.haml
- if @tweet.errors.any?
  - @tweet.errors.full_messages.each do |message|
    .error-message 3文字以上100文字以内でツイートしてください
    

app/views/layouts/_error_edit.html.haml
- if @tweet.errors.any?
  - @tweet.errors.full_messages.each do |message|
    .error-message 3文字以上100文字以内で編集してください

app/views/layouts/_notifications-new.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "new-signin")

app/views/layouts/_notifications.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash-index")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatAPP
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      .header
        %a.chatapp{href: "/"} chatAPP
        - if user_signed_in?
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "sign_out"
        - else
          = link_to "ログイン", user_session_path, class: "sign_in"
          = link_to "新規登録", new_user_registration_path, class: "sign_up"
    .main
      = yield
-# %div

app/views/tweets/_tweet.html.haml
-# .comments-chat-main
-#   .tweets-block
-#     .user-name
-#       = @tweet.user.name
-#     .messages
-#       = @tweet.text
-#     = link_to "編集", "/tweets/#{@tweet.id}/edit", method: :get, class: "comments-edit"
-#     = link_to "削除", "/tweets/#{@tweet.id}", method: :delete, class: "comments-delete"
-#     .time
-#       = @tweet.created_at.strftime("%Y/%m/%d %H:%M")

app/views/tweets/create.html.haml
-# .chat-main
-#   .tweets-block
-#     .user-name
-#       = current_user.name
-#     .messages
-#       ccc
-#       %i.fas.fa-ellipsis-h
-#     = link_to "返信", "#", class: "reply"
-#     .time
-#       = current_user.created_at
-# .tweets
-#   = link_to new_tweets_path do
-#     %i.fas.fa-pen

app/views/tweets/destroy.html.haml
.destroy-white
  .destroy-text
    削除が完了しました。
  = link_to "ツイート一覧へ戻る", "/", class: "destroy-tweet"

app/views/tweets/edit.html.haml
.new-field
  = form_tag("/tweets/#{@tweet.id}/edit", method: :patch) do
    = render 'layouts/error_edit'
    %h3.new-tweets
      編集する
    %textarea{placeholder: "編集する内容を入力してください", name: "text", class: "new-text"}
    %input{type: "submit", class: "new-submit"}/ 

app/views/tweets/index.html.haml
= render 'layouts/notifications'
.chat-main
  - @tweets.each do |tweet|
    .tweets-block
      .user-name
        = tweet.user.name
      .messages
        = tweet.text
      - if user_signed_in?
        = link_to "返信", "tweets/#{tweet.id}/comments", class: "reply"
      - else 
        = link_to "返信", "#", class: "reply"
      - if user_signed_in? && current_user.id == tweet.user_id
        = link_to "編集", "/tweets/#{tweet.id}/edit", method: :get, class: "edit"
        = link_to "削除", "/tweets/#{tweet.id}", method: :delete, class: "delete"
      .time
        = tweet.created_at.strftime("%Y/%m/%d %H:%M")
- if user_signed_in?
  .tweets
    = link_to new_tweet_path do
      %i.fas.fa-pen
    
-# - if user_signed_in? && current_user.id == tweet.user_id
-#   %li
-#     = link_to '編集', "/tweets/#{tweet.id}/edit", method: :get
-#   %li
-#     = link_to '削除', "/tweets/#{tweet.id}", method: :delete

app/views/tweets/new.html.haml
.new-field
  = form_for(@tweet) do |f|
    = render 'layouts/error'
    %h3.new-tweets
      ツイートする
    %textarea{placeholder: "ツイート文を入力してください", name: "text", class: "new-text"}
    %input{type: "submit", class: "new-submit"}/  

app/views/tweets/show.html.haml
.destroy-white
  .destroy-text
    削除が完了しました。
  = link_to "ツイート一覧へ戻る", "/", class: "destroy-tweet"